@startuml
class CryptoToken {
- name : String
- id : String
- price : Double
}

class CryptoTokenUser {
- cryptoTokenId : String
- userId : String
- amount : Double
}

class User {
- name : String
- id : String
- email : String
- password : String
}

class CryptoTokenDao {
- dynamoDBMapper : DynamoDBMapper
}

class CoinGeckoAPIClient {

}

class UserDao {
- dynamoDBMapper : DynamoDBMapper
}

class CryptoTokenUserDao {
- dynamoDBMapper : DynamoDBMapper
}

class UpdateCryptoTokenActivity {

}

class CreateCryptoTokenActivity {

}

class GetCryptoTokenActivity {

}

class CreateCryptoTokenUserActivity {

}

class UpdateCryptoTokenUserActivity {

}

class GetCryptoTokenUserActivity {

}

class CreateUserActivity {

}

class UpdateUserActivity {

}

class GetUserActivity {

}



CryptoToken --* CryptoTokenUser
CryptoTokenUser *-- User

CryptoTokenDao --o UpdateCryptoTokenActivity
CryptoTokenDao --o GetCryptoTokenActivity
CryptoTokenDao --o CreateCryptoTokenActivity

CryptoTokenUserDao --o UpdateCryptoTokenUserActivity
CryptoTokenUserDao --o GetCryptoTokenUserActivity
CryptoTokenUserDao --o CreateCryptoTokenUserActivity

UserDao --o UpdateUserActivity
UserDao --o CreateUserActivity
UserDao --o GetUserActivity




@enduml